2022-03-23 12:15:23,003 INFO    MainThread:1644811 [wandb_setup.py:_flush():71] setting env: {}
2022-03-23 12:15:23,003 INFO    MainThread:1644811 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-23 12:15:23,003 INFO    MainThread:1644811 [wandb_init.py:_log_setup():371] Logging user logs to /home/mazen/Projects/ttorch/examples/python/wandb/run-20220323_121523-1a1ex2kz/logs/debug.log
2022-03-23 12:15:23,004 INFO    MainThread:1644811 [wandb_init.py:_log_setup():372] Logging internal logs to /home/mazen/Projects/ttorch/examples/python/wandb/run-20220323_121523-1a1ex2kz/logs/debug-internal.log
2022-03-23 12:15:23,004 INFO    MainThread:1644811 [wandb_init.py:init():404] calling init triggers
2022-03-23 12:15:23,004 INFO    MainThread:1644811 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-03-23 12:15:23,004 INFO    MainThread:1644811 [wandb_init.py:init():460] starting backend
2022-03-23 12:15:23,004 INFO    MainThread:1644811 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-23 12:15:23,013 INFO    MainThread:1644811 [backend.py:ensure_launched():216] starting backend process...
2022-03-23 12:15:23,017 INFO    MainThread:1644811 [backend.py:ensure_launched():221] started backend process with pid: 1644832
2022-03-23 12:15:23,019 INFO    MainThread:1644811 [wandb_init.py:init():469] backend started and connected
2022-03-23 12:15:23,022 INFO    MainThread:1644811 [wandb_init.py:init():533] updated telemetry
2022-03-23 12:15:23,031 INFO    MainThread:1644811 [wandb_init.py:init():563] communicating current version
2022-03-23 12:15:23,869 INFO    MainThread:1644811 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-23 12:15:23,870 INFO    MainThread:1644811 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-23 12:15:24,504 INFO    MainThread:1644811 [wandb_init.py:init():606] starting run threads in backend
2022-03-23 12:15:27,154 WARNING MainThread:1644811 [wandb_init.py:init():952] interrupted
Traceback (most recent call last):
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 611, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 221, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 423, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/mazen/miniconda3/envs/jdt/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
